# Generated by Django 6.0.6 on 2026-06-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_product_warehouse'),
        ),
    ]
