# Generated by Django 6.0.6 on 2026-06-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_unique_product_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='available_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock available for new orders.'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='physical_stock',
            field=models.PositiveIntegerField(default=0, help_text='Actual stock physically present in the warehouse.'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock reserved for confirmed orders.'),
        ),
    ]
